### ISSUE TITLE
Provide Grafana dashboard and Prometheus Rules & Alerts

### ISSUE THREAD

**Issue by lukas-vlcek** [aiven/prometheus-exporter-plugin-for-opensearch#12]
Use [mixin approach](https://github.com/monitoring-mixins/docs) to generate Grafana compatible dashbhoard, Prometheus Rules and Alerts.

Sources of inspiration (all AL2):
- Elasticsearch mixin implemented for OpenShift Logging:
  -  https://github.com/lukas-vlcek/elasticsearch-mixin
  - https://github.com/openshift/elasticsearch-operator/tree/master/files
- Prometheus Alerts unit tests implemented as part of Elasticsearch-operator for OpenShift Logging:
  - https://github.com/openshift/elasticsearch-operator/blob/master/test/files/prometheus-unit-tests/test.yml

The idea is that the repository will get new sub-project folder to host related source files, on top of that there will be a new gradle task implemented to process mixin sources and run alerts tests. This means that as part of each new release of the prometheus-exporter plugin we could also run automated release of Grafana dashboard and Prometheus Rules & Alerts as well.

**Comment by Djeezus** [comment]
Hi, this sounds great !
just wondering ... is there any concrete work/planning already in the pipeline ?

**Comment by lukas-vlcek** [comment]
@Djeezus no specific plan but I would like to release initial dashboard soon. This ticket has some thumb-ups already. More importantly this will help a lot in my other goal which is to document individual metrics as well (see #35).

**Comment by vnovotny98** [comment]
Thanks for your job!
I can't wait to see it. I tried copying some ES dashboards and configuring myself, but it isn't only about replacing the es_ prefix with opensearch_ as mentioned here https://forum.opensearch.org/t/opensearch-jvm-monitor/10721/10.
There are many different metrics, but I couldn't find something like elasticsearch_cluster_health_status.
I hope this will be ready soon

**Comment by lukas-vlcek** [comment]
Literally, I am working on first dashboard release as we speak. It should be out in a few days. Stay tuned.

**Comment by Lobosque** [comment]
@lukas-vlcek would you mind sharing a preliminary version of the dashboard, if you have one?

**Comment by lukas-vlcek** [comment]
@Lobosque Sorry for late response. I plan to release some preliminary version by the end of this week. 🤞

**Comment by lukas-vlcek** [comment]
FYI: the code is being reviewed internally now. It seems that it will not be released this week (many people being OOO). Hopefully next week then.

**Comment by Kefa7y** [comment]
@lukas-vlcek any updates on the Grafana preliminary mixin? Really excited to try it out!

**Comment by lukas-vlcek** [comment]
@Kefa7y the internal team is working on it (there were some holidays in the meantime). I am sorry for the delay, I did not estimate correctly how quickly they can process this. Hopefully we will be able to move forward soon. Please, stay tuned.

**Comment by lukas-vlcek** [comment]
Hi, a quick heads up:
I created a new branch called `mixin` in this repo. It is completely independent branch (similarly to how `gh-pages` branch would be). It contains pre-release version of the mixin. I did not want to create a new repo for the mixin because the exporter plugin and the mixin are more or less related. I will be creating a first Release Candidate from it soon.

Stay tuned ❤️

**Comment by lukas-vlcek** [comment]
First release of the OpenSearch mixin has been released and announced: https://forum.opensearch.org/t/opensearch-mixin-1-0-0-rc-1-released/11717

Feedback welcome.

I created a new ["mixin" label](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/labels/mixin), you can use it when opening new tickets/PRs for the mixin.
