### ISSUE TITLE
enable GitHub dependabot for the repo

### ISSUE THREAD

**Issue by rursprung** [aiven/prometheus-exporter-plugin-for-opensearch#149]
i think it'd make sense to enable [GitHub dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates) for the repository (both for Gradle and the GitHub Actions) so that it can automate some dependency updates (it'll just create PRs for it, it's still up to you whether you want to merge them or not). if you'd be ok with that i could contribute a PR for this.

**Comment by lukas-vlcek** [comment]
Please send PR :-)

**Comment by lukas-vlcek** [comment]
Closed via https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/pull/150
