### ISSUE TITLE
Is it possible to add capability to collect metrics from selected indices?

### ISSUE THREAD

**Issue by tntruong723** [aiven/prometheus-exporter-plugin-for-opensearch#166]
From the open issue https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/321
> Hi,
Currently there is only an option to disable the metric collection for indices as a whole using the setting prometheus.indices: false. Is it possible to add support to collect metrics only for a limited set of indices?
Once the number of indices grow above 50 or so, we are seeing metrics collection is taking long resulting in gaps in the metrics scraped by Prometheus. In such cases, it would be nice to be able to monitor metrics for a few critical indices instead of disabling it completely.
Thanks
Jacob Mathews

I introduced the indices filter on my side. I will send a pull request soon.

**Comment by lukas-vlcek** [comment]
@tntruong723 Feel free to close this thicket as "completed". 😄

**Comment by lukas-vlcek** [comment]
Closing.

This feature has been [back-ported](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/pull/181) to `v1.3` branch and will be included in [`1.3.10.0` release](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/issues/178).

@tntruong723 Thank you for the great contribution.
