### ISSUE TITLE
Can you please tell the release schedule of the prometheus exporter plugin for  opensearch 2.9.0 

### ISSUE THREAD

**Issue by preeti-16** [aiven/prometheus-exporter-plugin-for-opensearch#205]
Can you please tell the release schedule of the prometheus exporter plugin for opensearch 2.9.0 version.

Thanks

**Comment by lukas-vlcek** [comment]
Hi,

please follow https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/pull/203 (ie. it is WIP, you can expect release soon).

HTH,
Lukáš

**Comment by lukas-vlcek** [comment]
The release ticket: https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/issues/207
